# Generated by Django 2.1.1 on 2019-07-25 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='goods_under',
            field=models.IntegerField(default=1, verbose_name='商品状态'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='goods_safeDate',
            field=models.IntegerField(verbose_name='保质期(月)'),
        ),
    ]
