# Generated by Django 2.1.1 on 2019-07-26 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0004_auto_20190725_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodstype',
            name='description',
            field=models.TextField(verbose_name='商品类型描述'),
        ),
    ]
